name: CI & Pack GovUK.Dfe.PersonsApi.Client

on:
  push:
    branches: [ main ]
    paths:
      - "src/GovUK.Dfe.PersonsApi.Client/**"
  pull_request:
    branches: [ main ]
    paths:
      - "src/GovUK.Dfe.PersonsApi.Client/**"

jobs:
  build-and-test:
    uses: ./.github/workflows/build-test-template.yml
    with:
      project_name: GovUK.Dfe.PersonsApi.Client
      project_path: src/GovUK.Dfe.PersonsApi.Client
      run_tests: false
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  pack-and-release:
    needs: build-and-test
    if: needs.build-and-test.result == 'success'
    uses: ./.github/workflows/pack-template.yml
    with:
      project_name: GovUK.Dfe.PersonsApi.Client
      project_path: src/GovUK.Dfe.PersonsApi.Client/GovUK.Dfe.PersonsApi.Client.csproj
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }} 